tap "opencode-ai/tap"
brew "ack"
brew "agg"
brew "asciinema"
brew "git"
brew "asdf"
brew "asimov"
brew "autoenv"
brew "autojump"
brew "bat"
brew "brew-cask-completion"
brew "brew-gem"
brew "fontconfig"
brew "openjdk"
brew "bundletool"
brew "cloudflare-wrangler"
brew "cloudflared"
brew "coreutils"
brew "dive"
brew "docker-completion", link: false
brew "docker", link: false
brew "eza"
brew "fd"
brew "findutils"
brew "fzf"
brew "gawk"
brew "ruby"
brew "gem-rake"
brew "gh"
brew "gifsicle"
brew "git-flow"
brew "git-lfs"
brew "git-open"
brew "gnu-sed"
brew "go"
brew "graphviz"
brew "grep"
brew "grip"
brew "gtop"
brew "htop"
brew "httpie"
brew "libomp"
brew "imagemagick"
brew "imagesnap"
brew "jj"
brew "jq"
brew "k9s"
brew "kubectx"
brew "lazydocker"
brew "lazygit"
brew "lazyjj"
brew "lazyjournal"
brew "llvm"
brew "mas"
brew "minikube"
brew "mintoolkit"
brew "moreutils"
brew "navi"
brew "neovim"
brew "nmap"
brew "nvm"
brew "nvtop"
brew "podman"
brew "podman-compose"
brew "podman-tui"
brew "portaudio"
brew "postgresql@15", link: true
brew "pyenv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "sevenzip"
brew "shellcheck"
brew "subversion"
brew "syncthing"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "tree"
brew "ttyrec"
brew "uni"
brew "up"
brew "watch"
brew "wget"
brew "xcodegen"
brew "yazi"
brew "yq"
brew "zsh"
brew "opencode-ai/tap/opencode"
cask "1password"
cask "1password-cli"
cask "aldente"
cask "alfred"
cask "android-platform-tools"
cask "app-tamer"
cask "balenaetcher"
cask "bartender"
cask "blender"
cask "calibre"
cask "cheetah3d"
cask "claude"
cask "coteditor"
cask "dash@6"
cask "deltawalker"
cask "devonagent"
cask "diffusionbee"
cask "discord"
cask "docker-desktop"
cask "drawio"
cask "epic-games"
cask "font-jetbrains-mono-nerd-font"
cask "fork"
cask "ganttproject"
cask "ghostty"
cask "github"
cask "gitup-app"
cask "gog-galaxy"
cask "google-chrome"
cask "handbrake-app"
cask "hex-fiend"
cask "imageoptim"
cask "istat-menus"
cask "iterm2"
cask "jetbrains-toolbox"
cask "ledger-live"
cask "little-snitch"
cask "lm-studio"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "obsidian"
cask "ollama-app"
cask "paragon-ntfs"
cask "plasticscm-cloud-edition"
cask "podman-desktop"
cask "portfolioperformance"
cask "rectangle"
cask "screenflow"
cask "signal"
cask "slack"
cask "snagit"
cask "steam"
cask "syncthing-app"
cask "thebrain"
cask "thonny"
cask "unity-hub"
cask "visual-studio-code"
cask "vlc"
cask "warp"
cask "zed"
cask "zen"
mas "1Password for Safari", id: 1569813296
mas "Affinity Designer 2", id: 1616831348
mas "Affinity Photo 2", id: 1616822987
mas "Affinity Publisher 2", id: 1606941598
mas "Amphetamine", id: 937984704
mas "Compressor", id: 424390742
mas "DaisyDisk", id: 411643860
mas "Day One", id: 1055511498
mas "DeathStranding", id: 6449748961
mas "Diffusers", id: 1666309574
mas "Disk Diet", id: 445512770
mas "Draw Things", id: 6444050820
mas "Final Cut Pro", id: 424389933
mas "GarageBand", id: 682658836
mas "Gemini 2", id: 1090488118
mas "Goodnotes", id: 1444383602
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "Logic Pro", id: 634148309
mas "MainStage", id: 634159523
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Money", id: 1185488696
mas "Motion", id: 434290957
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Perplexity", id: 6714467650
mas "Pixelmator Pro", id: 1289583905
mas "Pluralsight", id: 431748264
mas "Resident Evil 4", id: 6462360082
mas "RESIDENT EVIL 7 biohazard", id: 1640629241
mas "Save to Reader", id: 1640236961
mas "Scapple", id: 568020055
mas "Session Pal", id: 1515213004
mas "Spark Desktop", id: 6445813049
mas "Stockfish", id: 801463932
mas "stoic", id: 1312926037
mas "Tailscale", id: 1475387142
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "TickTick", id: 966085870
mas "Time Sink", id: 404363161
mas "Toggl Track", id: 957734279
mas "Vinegar", id: 1591303229
mas "WhatsApp", id: 310633997
mas "Xcode", id: 497799835
vscode "aaron-bond.better-comments"
vscode "alexdima.copy-relative-path"
vscode "alexkrechik.cucumberautocomplete"
vscode "altimateai.vscode-altimate-mcp-server"
vscode "andys8.jest-snippets"
vscode "appcypher.astro"
vscode "astro-build.astro-vscode"
vscode "bierner.markdown-mermaid"
vscode "bpruitt-goddard.mermaid-markdown-syntax-highlighting"
vscode "buenon.scratchpads"
vscode "byi8220.indented-block-highlighting"
vscode "carlosjs23.vscode-yarn-script"
vscode "chakrounanas.turbo-console-log"
vscode "christian-kohler.npm-intellisense"
vscode "cucumberopen.cucumber-official"
vscode "dave-hagedorn.jenkins-runner"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "deerawan.vscode-dash"
vscode "docker.docker"
vscode "donjayamanne.githistory"
vscode "dotenv.dotenv-vscode"
vscode "elringus.naninovel"
vscode "esbenp.prettier-vscode"
vscode "ex-codes.pine-script-syntax-highlighter"
vscode "firsttris.vscode-jest-runner"
vscode "formulahendry.code-runner"
vscode "formulahendry.github-actions"
vscode "foxundermoon.shell-format"
vscode "fwcd.kotlin"
vscode "gamunu.vscode-yarn"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "glenn2223.live-sass"
vscode "google.geminicodeassist"
vscode "grapecity.gc-excelviewer"
vscode "hediet.vscode-drawio"
vscode "howardzuo.vscode-npm-dependency"
vscode "innoverio.vscode-dbt-power-user"
vscode "janjoerke.jenkins-pipeline-linter-connector"
vscode "jebbs.plantuml"
vscode "jeffersonlicet.snipped"
vscode "jeremyrajan.webpack"
vscode "jjk.jjk"
vscode "kaisun.vscodevimacademy"
vscode "kimlimjustin.jsdoc-generator"
vscode "krizzdewizz.vscode-typescript-ast-explorer"
vscode "le0zh.vscode-regexp-preivew"
vscode "lee2py.aider-composer"
vscode "leizongmin.node-module-intellisense"
vscode "leodevbro.blockman"
vscode "mathiasfrohlich.kotlin"
vscode "mbehr1.dlt-logs"
vscode "mbehr1.fishbone"
vscode "mbehr1.smart-log"
vscode "mbehr1.vsc-lfs"
vscode "me-dutour-mathieu.vscode-github-actions"
vscode "mechatroner.rainbow-csv"
vscode "mikeburgh.xml-format"
vscode "mikestead.dotenv"
vscode "mohd-akram.vscode-html-format"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-playwright.playwright"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.live-server"
vscode "ms-vsliveshare.vsliveshare"
vscode "myml.vscode-markdown-plantuml-preview"
vscode "naco-siren.gradle-language"
vscode "netcorext.uuid-generator"
vscode "nicoespeon.abracadabra"
vscode "nicolasvuillamy.vscode-groovy-lint"
vscode "nopeslide.vscode-drawio-plugin-mermaid"
vscode "orta.vscode-jest"
vscode "p1c2u.jenkins"
vscode "panicbit.cargo"
vscode "parallelsdesktop.parallels-desktop"
vscode "prantlf.karma-problem-matchers"
vscode "rangav.vscode-thunder-client"
vscode "rbuckton.tsserver-live-reload"
vscode "redhat.fabric8-analytics"
vscode "redhat.java"
vscode "redhat.vscode-yaml"
vscode "richardwillis.vscode-gradle-extension-pack"
vscode "ritwickdey.liveserver"
vscode "rooveterinaryinc.roo-cline"
vscode "rust-lang.rust-analyzer"
vscode "rvest.vs-code-prettier-eslint"
vscode "ryanluker.vscode-coverage-gutters"
vscode "saber2pr.ts-ast-viewer"
vscode "samuelcolvin.jinjahtml"
vscode "saulecabrera.asls"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "sonarsource.sonarlint-vscode"
vscode "spywhere.guides"
vscode "statelyai.stately-vscode"
vscode "stevejpurves.cucumber"
vscode "svelte.svelte-vscode"
vscode "tabeyti.jenkins-jack"
vscode "thzt.vscode-ast"
vscode "tomasnikl.vscode-vitest-runner-for-pnpm"
vscode "unifiedjs.vscode-mdx"
vscode "vintharas.learn-vim"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vitest.explorer"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscodevim.vim"
vscode "vstirbu.vscode-mermaid-preview"
vscode "vue.volar"
vscode "wallabyjs.console-ninja"
vscode "wallabyjs.quokka-vscode"
vscode "wallabyjs.wallaby-vscode"
vscode "wayou.vscode-todo-highlight"
vscode "whizkydee.material-palenight-theme"
vscode "wix.vscode-import-cost"
vscode "xavierletohic.cucumber-feature-json-formatter"
vscode "yandeu.five-server"
vscode "yog.yog-plantuml-highlight"
vscode "yzhang.markdown-all-in-one"
