export default {
  name: "Homebrew desktop apps",
  type: "cask",
  packages: [
    //'adium',
    //'amazon-cloud-drive',
    //'atom',
    //'box-sync',
    //'comicbooklover',
    //'diffmerge',
    "docker", // docker for mac
    //'dropbox',
    //'evernote',
    //'flux',
    // "gpg-suite",
    //'ireadfast',
    "iterm2",
    //'little-snitch',
    // 'macbreakz',
    //'micro-snitch',
    // 'signal',
    //'macvim',
    // "sizeup",
    //'sketchup',
    "slack",
    // 'the-unarchiver',
    //'torbrowser',
    //'transmission',
    "visual-studio-code",
    //'vlc',
    // "xquartz",
  ],
}; 